### ISSUE TITLE
マイデザイン→再編集→アイテムカラー変更→カートに入れたとき、サムネイルが出ない

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/up-t-ios#170]
マイデザインにあるデザインを再編集
↓
アイテムカラーを変更
↓
カートに進む
としたときに、サムネイルが表示されない。
タップして詳細表示させても真っ白になります。
更に、そこから再編集しようとしても開けない。

金額がプリントなしの¥1,200になっているので、デザインが消えている？かもです。
![img_0013](https://user-images.githubusercontent.com/23730555/28858994-90bb591a-778f-11e7-9361-8e3a39d2a4ba.png)
![img_0012](https://user-images.githubusercontent.com/23730555/28858996-96a817c8-778f-11e7-9ab2-0fddf25d8ef0.PNG)

**Comment by take-iwa** [comment]
@alexeypolitov 追加情報です。
上のようなサムネイルが消えたデザインを注文すると以下のようなエラーが出ます。
↓iOSアプリ画面
![img_2919 png](https://user-images.githubusercontent.com/23730555/29099704-f568866a-7ce1-11e7-9133-2f2af934d5c7.png)

しかし、実は注文には入ってしまっていて、しかもデザイン情報が抜けてしまっています。
↓up-t管理画面
![img_04082017_194110_0](https://user-images.githubusercontent.com/23730555/29099803-8847da3a-7ce2-11e7-86ed-22501ee35039.png)

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください

**Comment by take-iwa** [comment]
@alexeypolitov 確認しましたが、同じでした。iphone6, up-tアプリバージョン1.5.7(1)

**Comment by alexeypolitov** [comment]
@take-iwa サーバー側で修正しました。ご確認ください

**Comment by take-iwa** [comment]
@alexeypolitov マイデザインから編集できないようになったので同じ手順で再現はできませんが、カート内でデザイン編集しても問題なかったのでOKかと思います。
